### ISSUE TITLE
Failed to activate the linter-pug package

### ISSUE THREAD

**Issue by sharvana85** [AtomLinter/atom-linter-pug#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [linter-pug](https://github.com/AtomLinter/atom-linter-pug) package 1.3.0

### Stack Trace

Failed to activate the linter-pug package

```
At Cannot find module 'atom-linter'

Error: Cannot find module 'atom-linter'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.provideLinter (/packages/linter-pug/lib/init.coffee:70:17)
    at Package.module.exports.Package.activateServices (/app.asar/src/package.js:393:69)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:221:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:335:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
```

### Non-Core Packages

```
linter 1.11.23 
linter-pug 1.3.0 
linter-pug-lint 0.2.0 
```

**Comment by Arcanemagus** [comment]
Can you please try re-installing the package? It looks like APM didn't install one of the dependencies.
