### ISSUE TITLE
[Linter] Error running pug-lint

### ISSUE THREAD

**Issue by in-in** [AtomLinter/atom-linter-pug#17]
![ea7b1](https://user-images.githubusercontent.com/8797432/28251945-6ddc0878-6a91-11e7-9885-f2844fa4c005.png)

from Atom console:
```
[Linter] Error running pug-lint Error: Column start (29) greater than line length (28) for line 206(…)
```
![56671](https://user-images.githubusercontent.com/8797432/28251946-7419e336-6a91-11e7-9563-dce4c48c94cf.png)

atom:  1.18.0
linter: 2.2.0
linter-pug: 1.3.1

**Comment by JonathanNickerson** [comment]
I'm having this issue also. Did you find a resolution?

**Comment by Arcanemagus** [comment]
@in-in If you are still seeing this are you able to share a file that reproduces this? This is due to a bug with `pug-lint` where it has reported a point in the document that doesn't exist, so finding and fixing this will benefit everyone who uses `pug-lint`.

**Comment by in-in** [comment]
Sorry, now i don't use pug

**Comment by brunowego** [comment]
Similar issue here.

```json
{
  "extends": "pug-lint-config-rowupper"
}
```

```
[Linter] Error running pug-lint Error: Cannot find module "pug-lint-config-rowupper" to extend
    at Linter._resolveExtendsFile (~/.atom/packages/linter-pug/node_modules/pug-lint/lib/linter.js:199:15)
    at Linter._extendConfiguration (~/.atom/packages/linter-pug/node_modules/pug-lint/lib/linter.js:157:29)
    at Linter.configure (~/.atom/packages/linter-pug/node_modules/pug-lint/lib/linter.js:80:12)
    at Object.<anonymous> (~/.atom/packages/linter-pug/lib/init.js:171:16)
    at Generator.next (<anonymous>)
    at step (~/.atom/packages/linter-pug/lib/init.js:3:273)
    at <anonymous>
```

**Comment by brunowego** [comment]
I find the prepend with `pug-lint-config-`. Just use only the name.

```json
{
  "extends": "rowupper"
}
```
