### ISSUE TITLE
SyntaxError: Unexpected token } in JSON at position 131

### ISSUE THREAD

**Issue by DSigmund** [AtomLinter/atom-linter-pug#9]
```
SyntaxError: Unexpected token } in JSON at position 131
    at Object.parse (native)
    at Object.exports.loadFromFile (C:\Users\sigmundd\.atom\packages\linter-pug\node_modules\pug-lint\lib\config-file.js:92:22)
    at Object.exports.getContent (C:\Users\sigmundd\.atom\packages\linter-pug\node_modules\pug-lint\lib\config-file.js:22:22)
    at Object.<anonymous> (C:\Users\sigmundd\.atom\packages\linter-pug\node_modules\pug-lint\lib\config-file.js:68:29)
    at filterPatterns (C:\Users\sigmundd\.atom\packages\linter-pug\node_modules\pug-lint\lib\config-file.js:149:14)
    at Array.filter (native)
    at findup (C:\Users\sigmundd\.atom\packages\linter-pug\node_modules\pug-lint\lib\config-file.js:135:21)
    at Object.exports.load (C:\Users\sigmundd\.atom\packages\linter-pug\node_modules\pug-lint\lib\config-file.js:66:5)
    at Object.getConfig (file:///C:/Users/sigmundd/.atom/packages/linter-pug/lib/init.coffee:42:27)
    at Object.provider.lint (file:///C:/Users/sigmundd/.atom/packages/linter-pug/lib/init.coffee:63:30)
    at promises.push.Promise.then._this.emitter.emit.linter (C:/Users/sigmundd/.atom/packages/linter/lib/linter-registry.js:63:26)
    at C:/Users/sigmundd/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (C:/Users/sigmundd/.atom/packages/linter/lib/linter-registry.js:60:18)
    at file:///C:/Users/sigmundd/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\sigmundd\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\sigmundd\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at file:///C:/Users/sigmundd/.atom/packages/linter/lib/editor-linter.js:86:22
    at file:///C:/Users/sigmundd/.atom/packages/linter/lib/helpers.coffee:25:18
```

Well... Every time the linter lints...

**Comment by Arcanemagus** [comment]
@DSigmund looks like this is coming from a configuration linter built into `pug-lint`, so it seems you have (had?) an invalid configuration file.

**Comment by DSigmund** [comment]
Jepp, after reinstalling atom and all plugins, the error is gone...
